import { createClient } from '@supabase/supabase-js';
import { Device, Banner, Order, PermissionRole, Accessory, FlashSale } from '../types';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || 'https://placeholder-project-id.supabase.co';
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsYWNlaG9sZGVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE1OTg4MTI4MDAsImV4cCI6MjI0NDQ0MTYwMH0.placeholder';

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

// ==========================================
// 1. Device (Product) Mappers
// ==========================================
export const mapDbProductToDevice = (db: any): Device => ({
  id: db.id,
  brand: db.brand,
  modelName: db.name,
  variant: db.variant || '',
  ram: db.ram || '',
  storage: db.storage || '',
  processor: db.processor || '',
  display: db.display || '',
  battery: db.battery || '',
  charging: db.charging || '',
  cameras: db.cameras || '',
  weight: db.weight || '',
  colors: Array.isArray(db.colors) ? db.colors : [],
  warranty: db.warranty || '',
  price: Number(db.price),
  offerPrice: Number(db.discount_price || db.price),
  stockCount: Number(db.stock || 0),
  description: db.description || '',
  specifications: db.specifications || {
    display: '',
    processor: '',
    ram: '',
    storage: '',
    battery: '',
    charging: '',
    camera: '',
    weight: '',
    connectivity: '',
    warranty: ''
  },
  features: Array.isArray(db.features) ? db.features : [],
  images: Array.isArray(db.images) ? db.images : [],
  videoUrl: db.video_url || undefined,
  status: db.status || 'available',
  views: Number(db.views || 0),
  sales: Number(db.sales || 0),
  deviceType: db.category || 'brand_new',

  // sealed fields
  factorySealed: db.factory_sealed ?? undefined,
  officialBrandWarrantyAvailable: db.official_brand_warranty ?? undefined,
  warrantyDuration: db.warranty_duration || undefined,
  launchDate: db.launch_date || undefined,
  invoiceAvailable: db.invoice_available ?? undefined,

  // preowned fields
  ownershipDetails: db.ownership || undefined,
  usedDuration: db.used_duration || undefined,
  originalPurchaseDate: db.original_purchase_date || undefined,
  purchaseBillAvailable: db.purchase_bill_available ?? undefined,
  boxAvailable: db.box_available ?? undefined,
  originalChargerAvailable: db.original_charger_available ?? undefined,
  originalCableAvailable: db.original_cable_available ?? undefined,
  earphonesAvailable: db.earphones_available ?? undefined,
  backCoverAvailable: db.back_cover_available ?? undefined,
  screenGuardApplied: db.screen_guard_applied ?? undefined,
  currentWarrantyStatus: db.current_warranty_status || undefined,
  warrantyExpiryDate: db.warranty_expiry_date || undefined,
  batteryHealth: db.battery_health ?? undefined,
  deviceConditionGrade: db.condition_grade || undefined,
  cosmeticConditionDescription: db.cosmetic_description || undefined,
  displayCondition: db.display_condition || undefined,
  frameCondition: db.frame_condition || undefined,
  backPanelCondition: db.back_panel_condition || undefined,
  biometricStatus: db.biometric_status || undefined,
  cameraCondition: db.camera_condition || undefined,
  speakerCondition: db.speaker_condition || undefined,
  microphoneCondition: db.microphone_condition || undefined,
  networkLockStatus: db.network_lock_status || undefined,
  repairHistory: db.repair_history || undefined,
  repairDescription: db.repair_description || undefined,
  qualityCheckStatus: Array.isArray(db.quality_checks) ? db.quality_checks : [],
  sellerNotes: db.seller_notes || undefined,

  // open box
  openBoxBoxAvailable: db.open_box_box ?? undefined,
  openBoxAccessoriesAvailable: db.open_box_accessories ?? undefined,
  openBoxWarrantyRemaining: db.open_box_warranty || undefined,
  openBoxActivationDate: db.open_box_activation || undefined,
  openBoxReason: db.open_box_reason || undefined,

  // refurbished
  refurbishedGrade: db.refurbished_grade || undefined,
  refurbishedPartsReplaced: db.refurbished_parts || undefined,
  refurbishedDate: db.refurbished_date || undefined,
  refurbishedBy: db.refurbished_by || undefined,
  refurbishedWarrantyOffered: db.refurbished_warranty || undefined,

  // demo unit
  demoStoreUsageDuration: db.demo_duration || undefined,
  demoUsageHours: db.demo_hours || undefined,
  demoPhysicalCondition: db.demo_condition || undefined,
  demoWarrantyStatus: db.demo_warranty || undefined,

  // instagram
  seenOnInstagram: db.seen_on_instagram ?? undefined,
  instagramPostUrl: db.instagram_url || undefined,
});

export const mapDeviceToDbProduct = (device: Partial<Device>): any => ({
  id: device.id,
  name: device.modelName,
  brand: device.brand,
  price: device.price,
  discount_price: device.offerPrice,
  stock: device.stockCount,
  category: device.deviceType,
  images: device.images,
  specifications: device.specifications,
  features: device.features,
  colors: device.colors,
  description: device.description,
  variant: device.variant,
  ram: device.ram,
  storage: device.storage,
  processor: device.processor,
  display: device.display,
  battery: device.battery,
  charging: device.charging,
  cameras: device.cameras,
  weight: device.weight,
  warranty: device.warranty,
  video_url: device.videoUrl,
  status: device.status,
  views: device.views,
  sales: device.sales,
  
  // preowned fields
  factory_sealed: device.factorySealed,
  official_brand_warranty: device.officialBrandWarrantyAvailable,
  warranty_duration: device.warrantyDuration,
  launch_date: device.launchDate,
  invoice_available: device.invoiceAvailable,
  ownership: device.ownershipDetails,
  used_duration: device.usedDuration,
  original_purchase_date: device.originalPurchaseDate,
  purchase_bill_available: device.purchaseBillAvailable,
  box_available: device.boxAvailable,
  original_charger_available: device.originalChargerAvailable,
  original_cable_available: device.originalCableAvailable,
  earphones_available: device.earphonesAvailable,
  back_cover_available: device.backCoverAvailable,
  screen_guard_applied: device.screenGuardApplied,
  current_warranty_status: device.currentWarrantyStatus,
  warranty_expiry_date: device.warrantyExpiryDate,
  battery_health: device.batteryHealth,
  condition_grade: device.deviceConditionGrade,
  cosmetic_description: device.cosmeticConditionDescription,
  display_condition: device.displayCondition,
  frame_condition: device.frameCondition,
  back_panel_condition: device.backPanelCondition,
  biometric_status: device.biometricStatus,
  camera_condition: device.cameraCondition,
  speaker_condition: device.speakerCondition,
  microphone_condition: device.microphoneCondition,
  network_lock_status: device.networkLockStatus,
  repair_history: device.repairHistory,
  repair_description: device.repairDescription,
  quality_checks: device.qualityCheckStatus,
  seller_notes: device.sellerNotes,
  open_box_box: device.openBoxBoxAvailable,
  open_box_accessories: device.openBoxAccessoriesAvailable,
  open_box_warranty: device.openBoxWarrantyRemaining,
  open_box_activation: device.openBoxActivationDate,
  open_box_reason: device.openBoxReason,
  refurbished_grade: device.refurbishedGrade,
  refurbished_parts: device.refurbishedPartsReplaced,
  refurbished_date: device.refurbishedDate,
  refurbished_by: device.refurbishedBy,
  refurbished_warranty: device.refurbishedWarrantyOffered,
  demo_duration: device.demoStoreUsageDuration,
  demo_hours: device.demoUsageHours,
  demo_condition: device.demoPhysicalCondition,
  demo_warranty: device.demoWarrantyStatus,
  seen_on_instagram: device.seenOnInstagram,
  instagram_url: device.instagramPostUrl,
});

// ==========================================
// 2. Banner Mappers
// ==========================================
export const mapDbBannerToBanner = (db: any): Banner => ({
  id: db.id,
  imageUrl: db.image_url,
  title: db.title,
  redirectLink: db.redirect_link || '',
  startDate: db.start_date || '',
  endDate: db.end_date || '',
  slideshowTimer: db.slideshow_timer || 5,
  enabled: db.active,
  order: db.priority,
});

export const mapBannerToDbBanner = (banner: Partial<Banner>): any => ({
  id: banner.id,
  title: banner.title,
  subtitle: banner.title,
  image_url: banner.imageUrl,
  active: banner.enabled,
  priority: banner.order,
  redirect_link: banner.redirectLink,
  start_date: banner.startDate,
  end_date: banner.endDate,
  slideshow_timer: banner.slideshowTimer,
});

export const mapDbOrderToOrder = (db: any): Order => ({
  id: db.id,
  customerEmail: db.customer_email || db.email || 'walkin@customer.com',
  customerName: db.customer_name,
  customerPhone: db.phone,
  shippingAddress: db.address,
  items: db.products,
  subtotal: Number(db.subtotal || db.total),
  discount: Number(db.discount || 0),
  gstAmount: Number(db.gst_amount || 0),
  deliveryFee: Number(db.delivery_fee || 0),
  total: Number(db.total),
  estimatedDeliveryDate: db.estimated_delivery_date || 'N/A',
  status: db.status,
  orderDate: db.created_at || db.order_date || new Date().toISOString(),
  deliveryType: db.delivery_type || 'home_delivery',
  isPreorder: db.is_preorder || false,
  pickupDate: db.pickup_date,
  pickupTime: db.pickup_time,
  pickupOtp: db.pickup_otp,
  collectedBy: db.collected_by,
  collectionTime: db.collection_time,
  deliveryPartner: db.delivery_partner,
  deliveryExecutiveName: db.delivery_executive_name,
  deliveryExecutivePhone: db.delivery_executive_phone,
  trackingNumber: db.tracking_number,
  paymentMethod: db.payment_method || 'cod',
  paymentStatus: db.payment_status || 'pending',
  timeline: Array.isArray(db.timeline) ? db.timeline : [],
  internalNotes: Array.isArray(db.internal_notes) ? db.internal_notes : [],
  callLogs: Array.isArray(db.call_logs) ? db.call_logs : [],
});

export const mapOrderToDbOrder = (order: Partial<Order>): any => ({
  id: order.id,
  customer_name: order.customerName,
  phone: order.customerPhone,
  address: order.shippingAddress,
  products: order.items,
  total: order.total,
  status: order.status,
  created_at: order.orderDate,
  
  // extra fields for CRM consistency
  customer_email: order.customerEmail,
  subtotal: order.subtotal,
  discount: order.discount,
  gst_amount: order.gstAmount,
  delivery_fee: order.deliveryFee,
  estimated_delivery_date: order.estimatedDeliveryDate,
  delivery_type: order.deliveryType,
  is_preorder: order.isPreorder,
  pickup_date: order.pickupDate,
  pickup_time: order.pickupTime,
  pickup_otp: order.pickupOtp,
  collected_by: order.collectedBy,
  collection_time: order.collectionTime,
  delivery_partner: order.deliveryPartner,
  delivery_executive_name: order.deliveryExecutiveName,
  delivery_executive_phone: order.deliveryExecutivePhone,
  tracking_number: order.trackingNumber,
  payment_method: order.paymentMethod,
  payment_status: order.paymentStatus,
  timeline: order.timeline,
  internal_notes: order.internalNotes,
  call_logs: order.callLogs,
});

// ==========================================
// 4. Accessory Mappers
// ==========================================
export const mapDbAccessoryToAccessory = (db: any): Accessory => ({
  id: db.id,
  category: db.category,
  brand: db.brand,
  name: db.name,
  price: Number(db.price),
  offerPrice: Number(db.discount_price || db.price),
  stockCount: Number(db.stock || 0),
  description: db.description || '',
  colors: Array.isArray(db.colors) ? db.colors : [],
  images: Array.isArray(db.images) ? db.images : [],
  status: db.status || 'available',
  specifications: db.specifications || {},
  features: Array.isArray(db.features) ? db.features : [],
  views: Number(db.views || 0),
  sales: Number(db.sales || 0),
  createdAt: db.created_at || new Date().toISOString(),
});

export const mapAccessoryToDbAccessory = (acc: Partial<Accessory>): any => ({
  id: acc.id,
  category: acc.category,
  brand: acc.brand,
  name: acc.name,
  price: acc.price,
  discount_price: acc.offerPrice,
  stock: acc.stockCount,
  description: acc.description,
  colors: acc.colors,
  images: acc.images,
  status: acc.status,
  specifications: acc.specifications,
  features: acc.features,
  views: acc.views,
  sales: acc.sales,
  created_at: acc.createdAt,
});

// ==========================================
// 5. Flash Sale Mappers
// ==========================================
export const mapDbFlashSaleToFlashSale = (db: any): FlashSale => ({
  id: db.id,
  deviceId: db.device_id,
  discountPercentage: Number(db.discount_percentage || 0),
  stockLimit: Number(db.stock_limit || 0),
  soldCount: Number(db.sold_count || 0),
  startTime: db.start_time || new Date().toISOString(),
  endTime: db.end_time || new Date().toISOString(),
  enabled: db.enabled,
});

export const mapFlashSaleToDbFlashSale = (fs: Partial<FlashSale>): any => ({
  id: fs.id,
  device_id: fs.deviceId,
  discount_percentage: fs.discountPercentage,
  stock_limit: fs.stockLimit,
  sold_count: fs.soldCount,
  start_time: fs.startTime,
  end_time: fs.endTime,
  enabled: fs.enabled,
});
